"""Generate the robot description from config/robot.yaml.

URDF rather than USD on purpose: URDF is plain text, version-independent and
reviewable in a diff, and Isaac Lab ships a converter (`UrdfConverter`) that
turns it into a USD articulation at load time.  A hand-built USD would have to
track the Isaac Sim schema version; this does not.

Frames match reflex_quad/robot.py exactly:
    hip  rotates about -y so that +angle swings the foot toward +x (forward)
    knee rotates about the same axis, 0 = straight leg
"""
from __future__ import annotations

from pathlib import Path

from .config import load_yaml

TEMPLATE_HEADER = """<?xml version="1.0"?>
<!-- generated by reflex_quad/asset_builder.py - do not edit by hand -->
<robot name="reflex_quad">
  <material name="body_grey"><color rgba="0.30 0.32 0.35 1.0"/></material>
  <material name="link_blue"><color rgba="0.20 0.45 0.75 1.0"/></material>
  <material name="foot_dark"><color rgba="0.12 0.12 0.14 1.0"/></material>
"""


def _box_inertia(m, x, y, z):
    return (m / 12 * (y * y + z * z), m / 12 * (x * x + z * z), m / 12 * (x * x + y * y))


def _capsule_inertia(m, r, length):
    ixx = m / 12 * (3 * r * r + length * length)
    return (ixx, ixx, 0.5 * m * r * r)


def build_urdf(robot_cfg: dict | None = None) -> str:
    cfg = robot_cfg or load_yaml("robot.yaml")
    b = cfg["body"]
    leg = cfg["leg"]
    l1, l2 = leg["upper_length"], leg["lower_length"]
    m1, m2 = leg["upper_mass"], leg["lower_mass"]
    r = leg["foot_radius"]
    lo_hip, hi_hip = leg["hip_limit"]
    lo_knee, hi_knee = leg["knee_limit"]

    ixx, iyy, izz = _box_inertia(b["mass"], b["length"], b["width"], b["height"])
    out = [TEMPLATE_HEADER]
    out.append(f"""  <link name="body">
    <visual>
      <geometry><box size="{b['length']} {b['width']} {b['height']}"/></geometry>
      <material name="body_grey"/>
    </visual>
    <collision>
      <geometry><box size="{b['length']} {b['width']} {b['height']}"/></geometry>
    </collision>
    <inertial>
      <mass value="{b['mass']}"/>
      <inertia ixx="{ixx:.6f}" ixy="0" ixz="0" iyy="{iyy:.6f}" iyz="0" izz="{izz:.6f}"/>
    </inertial>
  </link>
""")

    for spec in cfg["legs"]:
        name = spec["name"]
        hx, hy = spec["hip_x"], spec["hip_y"]
        for tag, length, mass, parent, origin, axis_limits in (
            ("upper", l1, m1, "body", (hx, hy, -b["height"] / 2), (lo_hip, hi_hip)),
            ("lower", l2, m2, f"{name}_upper", (0.0, 0.0, -l1), (lo_knee, hi_knee)),
        ):
            joint = "hip" if tag == "upper" else "knee"
            cix, ciy, ciz = _capsule_inertia(mass, r, length)
            out.append(f"""  <joint name="{name}_{joint}" type="revolute">
    <parent link="{parent}"/>
    <child link="{name}_{tag}"/>
    <origin xyz="{origin[0]} {origin[1]} {origin[2]}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="{axis_limits[0]}" upper="{axis_limits[1]}" effort="4.0" velocity="12.0"/>
    <dynamics damping="0.02" friction="0.0"/>
  </joint>
  <link name="{name}_{tag}">
    <visual>
      <origin xyz="0 0 {-length / 2}"/>
      <geometry><cylinder radius="{r * 0.8}" length="{length}"/></geometry>
      <material name="link_blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 {-length / 2}"/>
      <geometry><cylinder radius="{r * 0.8}" length="{length}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 {-length / 2}"/>
      <mass value="{mass}"/>
      <inertia ixx="{cix:.8f}" ixy="0" ixz="0" iyy="{ciy:.8f}" iyz="0" izz="{ciz:.8f}"/>
    </inertial>
  </link>
""")
        # foot: a small sphere, and the only body that touches the ground.
        # The contact sensor is attached here, so it must be its own link.
        out.append(f"""  <joint name="{name}_foot_fixed" type="fixed">
    <parent link="{name}_lower"/>
    <child link="{name}_foot"/>
    <origin xyz="0 0 {-l2}"/>
  </joint>
  <link name="{name}_foot">
    <visual><geometry><sphere radius="{r}"/></geometry><material name="foot_dark"/></visual>
    <collision><geometry><sphere radius="{r}"/></geometry></collision>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
    </inertial>
  </link>
""")
    out.append("</robot>\n")
    return "".join(out)


def write_urdf(path: Path | str = "assets/reflex_quad.urdf") -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_urdf())
    return path


if __name__ == "__main__":
    print(write_urdf())
